import { Realisation } from "./realisation";

export const REALISATION: Realisation[] = [
	{
		id: 1,
		name: "Modélisation du système solaire",
		picture: "assets/SpaceOdyssey.png",
		description:
			"Modélisation 3D du système solaire offrant la possibilité d'accéder à des informations sur les différentes planètes et télescopes, en les sélectionnant ou en les recherchant via une barre de navigation.",
		types: [
			"NextJS",
			"React",
			"TypeScript",
			"SCSS",
			"ReactThreeFiber",
			"Zustand",
			"REST",
			"NodeJS",
			"Express",
		],
		created: new Date(),
		url: "https://space-odyssey.vercel.app/",
		title: "Space Odyssey",
	},
	{
		id: 2,
		name: "Application de trading",
		picture: "assets/DistrictMoney.png",
		description:
			"Application de trading permettant de s'initier au monde financier et à la Bourse, en simulant notamment la gestion d'un portfeuille boursier au travers d'achat et de vente d'actions,  mais sans avoir à risquer son argent.",
		types: [
			"NextJS",
			"React",
			"TypeScript",
			"SCSS",
			"Zustand",
			"Jest",
			"Firebase",
			"REST",
			"NodeJS",
			"Express",
		],
		created: new Date(),
		url: "https://district-money.vercel.app/",
		title: "District Money",
	},
	{
		id: 4,
		name: "Réseau social",
		picture: "assets/Awayver.png",
		description:
			"Réseau social permettant de discuter, échanger des conseils ou des recommandations avec d'autres personnes à travers le monde et permettant de publier des photos ou expériences de voyages.",
		types: [
			"NextJS",
			"React",
			"TypeScript",
			"Jest",
			"MongoDB",
			"Prisma",
			"NextAuth",
			"ReactQuery",
			"GraphQL",
		],
		created: new Date(),
		url: "https://awayver.vercel.app/",
		title: "Awayver",
	},
	{
		id: 4,
		name: "Composition musicale",
		picture: "assets/Songarden.png",
		description:
			"Réalisation d'une application permettant de composer ses propres mélodies en choisissant parmi une dizaine d'instruments et en visualisant les notes en temps réel.",
		types: ["NextJS", "React", "TypeScript", "Zustand"],
		created: new Date(),
		url: "https://songarden.vercel.app/",
		title: "Songarden",
	},
	{
		id: 5,
		name: "Application pour photographe",
		picture: "assets/Photographie.png",
		description:
			"Réalisation d'une application facilitant le partage de photos prises lors d'un shooting professionnel. Les modèles peuvent ensuite sélectionner les photos à retoucher.",
		types: ["NextJS", "React", "TypeScript", "NodeJS", "GoogleDriveAPI"],
		created: new Date(),
		url: "https://josephparisvisuals.vercel.app/",
		title: "Joseph Paris Visuals",
	},
	{
		id: 6,
		name: "Application pour restaurant",
		picture: "assets/NormandVoyageur.png",
		description:
			"Application pour un restaurant, Le Normand Voyageur, proposant de nombreux plats rencontrés lors de mes différents voyages en Europe, Afrique et Amérique du Sud.",
		types: ["React", "JavaScript", "FramerMotion", "Firebase"],
		created: new Date(),
		url: "https://adrienvers.github.io/site-de-e-commerce/",
		title: "Le Normand Voyageur",
	},
	{
		id: 7,
		name: "Clone de YouTube",
		picture: "assets/Youtube.png",
		description:
			"Application permettant de visualiser les films qui sortiront prochainement au cinéma, les films les plus vus, le tout avec le design de la plateforme YouTube.",
		types: ["React", "Firebase"],
		created: new Date(),
		url: "https://adrienvers.github.io/youtube-clone/",
		title: "Youtube Clone",
	},
	{
		id: 8,
		name: "Roue de la nourriture",
		picture: "assets/Roue.png",
		description:
			"Site web proposant de lancer une roue qui déterminera (en fonction de la puissance de votre lancé) quel plat vous allez déguster. Vous pouvez ainsi choisir de manière amusante votre repas sans avoir à vous préoccuper de la décision.",
		types: ["HTML", "CSS", "JavaScript"],
		created: new Date(),
		url: "https://adrienvers.github.io/Roue-de-la-fortune/",
		title: "Roue de la nourriture",
	},
	{
		id: 9,
		name: "Portes motorisées",
		picture: "assets/Industrie.png",
		description:
			"Site web permettant de simuler l'ouverture et la fermeture de portes industrielles, mais aussi connaître les états de fermeture ou d'ouverture en temps réel. La simulation permet également de réaliser un arrêt d'urgence.",
		types: ["HTML", "CSS", "JavaScript"],
		created: new Date(),
		url: "https://adrienvers.github.io/IHM-Industrielle/",
		title: "IHM Industrielle",
	},
	{
		id: 10,
		name: "Jeu de stratégie",
		picture: "assets/LittleSlayer.png",
		description:
			"Jeu de stratégie permettant aux joueurs d'incarner un personnage nain et de profiter d'une large sélection d'armes amusantes. En jouant à ce jeu, les utilisateurs doivent utiliser leur intelligence pour gagner.",
		types: ["Unity", "Csharp"],
		created: new Date(),
		url: "https://github.com/AdrienVers/Little-Slayer",
		title: "Little Slayer",
	},
];
