import { Formation } from "./skill";

export const FORMATION: Formation[] = [
	{
		id: 1,
		name: "Formation C# / ASP.NET (2023)",
		image: "NET7",
		tags: [
			"C# v11 (POO)",
			".NET 7 (Entity Framework Core, LINQ)",
			"SQL Server",
			"Docker",
		],
		link: "https://hts-learning.com/shop/course/infos/csharp",
		owner: "Christophe Mommer (Senior FullStack)",
	},
	{
		id: 2,
		name: "Formation NextJS (2022)",
		image: "Ecosystem",
		tags: [
			"NextJS v13",
			"React v18",
			"TypeScript",
			"Zod",
			"React-Query",
			"Prisma",
			"NextAuth",
			"RTL / Jest",
		],
		link: "https://codelynx.dev/nextreact",
		owner: "Melvyn Malherbe (Senior FullStack)",
	},
	{
		id: 3,
		name: "Formation TypeScript (2022)",
		image: "Types",
		tags: ["TypeScript", "React v17", "Jest", "React Testing Library"],
		link: "https://training.mikecodeur.com",
		owner: "Mickaël Cabanas (Senior FullStack)",
	},
	{
		id: 4,
		name: "Formation sur les tests (2022)",
		image: "Tests",
		tags: [
			"Test unitaire (React Testing Library / Jest)",
			"Test d'intégration (Cypress)",
		],
		link: "https://formations.mikecodeur.com",
		owner: "Mickaël Cabanas (Senior FullStack)",
	},
	{
		id: 5,
		name: "Formation React (2022)",
		image: "Hooks",
		tags: [
			"React v18",
			"TypeScript",
			"Zod",
			"React-Query",
			"Prisma",
			"NextAuth",
			"RTL / Jest",
		],
		link: "https://codelynx.dev/nextreact",
		owner: "Melvyn Malherbe (Senior FullStack)",
	},
	{
		id: 6,
		name: "Formation Frontend (2022)",
		image: "Frameworks",
		tags: [
			"React",
			"Redux",
			"VueJS",
			"Angular",
			"Méthodes Agiles (SCRUM, KANBAN)",
			"SEO",
		],
		link: "https://openclassrooms.com/fr/courses/7150626-utilisez-le-state-manager-redux-pour-gerer-l-etat-de-vos-applications",
		owner: "OpenClassrooms (Formation en ligne)",
	},
	{
		id: 7,
		name: "Formation d'ingénieur (2017-2020)",
		image: "ESMESudria",
		tags: ["HTML", "CSS", "JavaScript", "C# (POO)", "MySQL", "Réseau"],
		link: "https://www.esme.fr/formation-ingenieur/ingenieur-intelligence-artificielle",
		owner: "ESME Sudria (Ecole d'ingénieur)",
	},
];
